/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CsSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
    interface CsTooltip {
        "tooltipText": string;
    }
}
declare global {
    interface HTMLCsSideDrawerElement extends Components.CsSideDrawer, HTMLStencilElement {
    }
    var HTMLCsSideDrawerElement: {
        prototype: HTMLCsSideDrawerElement;
        new (): HTMLCsSideDrawerElement;
    };
    interface HTMLCsTooltipElement extends Components.CsTooltip, HTMLStencilElement {
    }
    var HTMLCsTooltipElement: {
        prototype: HTMLCsTooltipElement;
        new (): HTMLCsTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "cs-side-drawer": HTMLCsSideDrawerElement;
        "cs-tooltip": HTMLCsTooltipElement;
    }
}
declare namespace LocalJSX {
    interface CsSideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface CsTooltip {
        "tooltipText"?: string;
    }
    interface IntrinsicElements {
        "cs-side-drawer": CsSideDrawer;
        "cs-tooltip": CsTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cs-side-drawer": LocalJSX.CsSideDrawer & JSXBase.HTMLAttributes<HTMLCsSideDrawerElement>;
            "cs-tooltip": LocalJSX.CsTooltip & JSXBase.HTMLAttributes<HTMLCsTooltipElement>;
        }
    }
}
